<?php


$lang_text      = array(
    '500_desc' => '數據庫出錯。',
    '500_title' => '這個頁面不是',
    '404_desc' => '這個頁面不是',
    '404_title' => '404',
    '404_text' => '沒有!!!',
    'Error_1' => '錯誤!',
    'Error_2' => '信息無效',
    'Download_file' => '下載',
    'Video_format' => '格式',
    'Internet_connection_search_error' => '搜索無法完成，請檢查Internet連接並重試',
	'not_link_media' => '鏈接被破壞或錯誤寫入',
	'not_service_media' => '此服務暫時無法使用',
	'Menu_header' => '菜單',
	'Terms_of_Use' => '使用條款',
	'Privacy_Policy' => '隱私政策',
	'Menu_header' => '菜單',
	'Back_search' => '回報',
	'languages_header' => '語言',
	'Text_1' => '在線視頻下載器',
	'Text_2' => '從YouTube，Instagram，Facebook，Twitter和許多其他網站下載視頻',
	'Enter_url' => '輸入視頻鏈接...',
	'Get_link_btn' => '下載鏈接',
	'Get_link_btn_load' => '充電器...',
	'help_home' => '¿您需要幫助才能下載視頻?',
	'site_Supported' => '查看我們擁有的兼容網站 <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => '查看我們擁有的兼容網站 ('.websites_supported().')',
	'click_more_home' => '查看所有支持的站點',
	'help_page' => '下載視頻的步驟',
	'text_down_1' => 'FORMAT',
	'text_down_2' => '質量',
	'text_down_3' => 'SIZE',
	'no_bot_user' => '確認我不是機器人',
	'history' => '歷史',
	'Settings' => '設置',
	'Sign_off' => '登出',
	'login' => '登錄',
	'register' => '寄存器',
	'share' => '分享',
	'url_share' => '分享網址：',
	'original_url' => '原始網址：',
	'copy' => '複製',
	'source_views' => '意見來源',
	'empty_modal' => '你還沒有歷史',
	'invalid_username_or_password' => '用戶名或密碼無效',
	'reset_password' => '重設密碼',
	'email_sent' => '電郵發送成功',
    'email_not_exist' => '電子郵件不存在',
    'username' => '用戶名',
    'password' => '密碼',
    'email' => '電子郵件',
    'terms__privacy' => '我同意使用條款和隱私政策',
	'please_wait' => '請耐心等待..',
	'please_check_details' => '請查看詳細信息',
	'username_is_taken' => '用戶名已存在',
	'username_invalid_characters' => '用戶名字符無效',
    'email_exists' => '這封電子郵件已經在使用中',
    'email_invalid_characters' => '電子郵件無效',
	'successfully_joined_desc' => '註冊成功！ 我們已向您發送了一封電子郵件，請檢查您的收件箱/垃圾郵件以驗證您的帳戶。',	
	'we_have_a_problem' => '我們有一個問題再試一次',
	'got_your_password' => '有你的密碼？',
	'request_new_password' => '需要新密碼',
	'incorrect_information' => '信息不正確',
	'password_not_match' => '密碼不匹配',
    'password_is_short' => '密碼太短',
	'confirm_password' => '確認密碼',
	'confirm_email' => '已使用新密碼發送電子郵件',
	'confirm_email_error' => '驗證您的數據時出錯',
	'info_plataforma' => ''. $config['name_site'].' 您可以從最受歡迎的網站下載免費視頻，例如：Youtube，Dailymotion，Facebook，Instagram，Vimeo等。單擊一下，視頻將與所有可用格式一起顯示，例如MP4，FLV，3GP， WMV，WEBM，MP3等等。所以，您需要做的就是以您喜歡的格式下載視頻....',	
	'Support_plan' => '支持',	
	'Support_plan_1' => '無限下載',	
	'Support_plan_2' => '易於使用的設計',	
	'Support_plan_3' => '下載歷史記錄',	
	'Support_plan_4' => '您的共享鏈接的統計信息',	
	'Analyzing_video_links' => '分析視頻鏈接',
	'info_plataforma_2' => ''.$config['name_site'].' 這是一個免費的在線網站下載視頻。 無需安裝軟件。 您只需要向我們提供包含您要下載的視頻的鏈接。 點擊“下載”按鈕，然後就完成了！',	
	'info_plataforma_3' => '無限制和高速視頻下載從YouTube，TED，Soundcloud，Bandcamp下載音頻',
	'Online_Video_Downloader' => '在線下載視頻',
	'Any_Video_ite' => '任何視頻，任何網站',
	'Download_Audios' => '下載音頻',
	'report_link_1' => '抱歉，出了點問題，我們在您的鏈接上找不到任何視頻。',
	'report_link_2' => '這是你輸入的內容:',
	'report_link_3' => '錯誤是',
	'report_link_4' => '訪問上一個鏈接以確保在將非私有視頻放入下載程序之前有效.',
	'report_link_5' => '發送報告',
	'message_link_ok' => '謝謝你幫助我們 :)',	
);

$name_lang 	= '中國';
$url_lang 	= 'chinese';
$img_lang 	= 'https://i.imgur.com/yX70U5C.png';
  	
?>

