<?php


$lang_text      = array(
    '500_desc' => 'Error with the Database.',
    '500_title' => 'This page is not',
    '404_desc' => 'This page is not',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'the information is not valid',
    'Download_file' => 'Download',
    'Video_format' => 'Format',
    'Internet_connection_search_error' => 'The search can not be completed, check the Internet connection and try again',
	'not_link_media' => 'The Link is broken or Wrong written',
	'not_service_media' => 'This service is not available at the moment',
	'Menu_header' => 'Menu',
	'Terms_of_Use' => 'Terms of use',
	'Privacy_Policy' => 'Privacy Policy',
	'Menu_header' => 'Menu',
	'Back_search' => 'back',
	'languages_header' => 'Language',
	'Text_1' => 'Online video downloader',
	'Text_2' => 'Download videos from YouTube, Instagram, Facebook, Twitter and many other websites',
	'Enter_url' => 'Enter the video link ...',
	'Get_link_btn' => 'GET DOWNLOADS LINK',
	'Get_link_btn_load' => 'Loader...',
	'help_home' => 'Need help downloading videos?',
	'site_Supported' => 'See the compatible sites we have <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => 'See the compatible sites we have ('.websites_supported().')',
	'click_more_home' => 'See all supported sites',
	'help_page' => 'Steps to download videos',
	'text_down_1' => 'FORMAT',
	'text_down_2' => 'QUALITY',
	'text_down_3' => 'SIZE',
	'no_bot_user' => 'Verify I&#39;m not a bot',
	'history' => 'History',
	'Settings' => 'Settings',
	'Sign_off' => 'Sign out',
	'login' => 'Log in',
	'register' => 'Register',
	'share' => 'Share',
	'url_share' => 'Share url:',
	'original_url' => 'Original url:',
	'copy' => 'copy',
	'source_views' => 'Source of views',
	'empty_modal' => 'You do not have a history yet',
	'invalid_username_or_password' => 'Invalid username or password',
	'reset_password' => 'Reset Password',
	'email_sent' => 'E-mail sent successfully',
    'email_not_exist' => 'E-mail not exist',
    'username' => 'Username',
    'password' => 'Password',
    'email' => 'E-mail',
    'terms__privacy' => 'I agree to the terms of use and privacy policy',
	'please_wait' => 'Please wait..',
	'please_check_details' => 'Please check the details',
	'username_is_taken' => 'Username is taken',
	'username_invalid_characters' => 'Invalid username characters',
    'email_exists' => 'This e-mail is already in use',
    'email_invalid_characters' => 'E-mail is invalid',
	'successfully_joined_desc' => 'Registration successful! We have sent you an email, Please check your inbox/spam to verify your account.',	
	'we_have_a_problem' => 'We have a problem try again',
	'got_your_password' => 'Got your password?',
	'request_new_password' => 'Request new password',
	'incorrect_information' => 'Incorrect Information',
	'password_not_match' => 'Password not match',
    'password_is_short' => 'Password is too short',
	'confirm_password' => 'Confirm Password',
	'confirm_email' => 'An email has been sent with the new password',
	'confirm_email_error' => 'there was an error to verify your data',
	'info_plataforma' => ''.$config['name_site'].' can download free videos from the most popular sites, for example: Youtube, Dailymotion, Facebook, instagram, Vimeo Etc. After a single click, the video will be displayed along with all the available formats, such as MP4, FLV, 3GP, WMV, WEBM, MP3, etc. So, all you need to do is download the videos in your preferred format. ',	
	'Support_plan' => 'Support',	
	'Support_plan_1' => 'Unlimited downloads',	
	'Support_plan_2' => 'Easy to use design',	
	'Support_plan_3' => 'Download history',	
	'Support_plan_4' => 'Statistics of your shared links',	
	'Analyzing_video_links' => 'Analyzing video links',
	'info_plataforma_2' => ''.$config['name_site'].' It is a free online website to download videos. No software installation is required. You just need to provide us with a link that contains the video you want to download. Click on the Download button, then things are done!',	
	'info_plataforma_3' => 'Unlimited and high-speed video download Download audios from YouTube, TED, Soundcloud, Bandcamp',
	'Online_Video_Downloader' => 'Download video online',
	'Any_Video_ite' => 'Any video, any site',
	'Download_Audios' => 'Download audios',
	'report_link_1' => 'Sorry, something went wrong, we could not find any video on your link.',
	'report_link_2' => 'Here is what you have entered:',
	'report_link_3' => 'Error',
	'report_link_4' => 'Visit the previous link to make sure there is a non-private video that works before putting it in the download program.',
	'report_link_5' => 'Send report',
	'message_link_ok' => 'Thanks for helping us :)',
);

$name_lang 	= 'English';
$url_lang 	= 'english';
$img_lang 	= 'https://i.imgur.com/cWawBzY.png';
  	
?>

