<?php


$lang_text      = array(
    '500_desc' => 'Erreur avec la base de données.',
    '500_title' => 'Cette page n&#39;est pas',
    '404_desc' => 'Cette page n&#39;est pas',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Erreur!',
    'Error_2' => 'l&#39;information n&#39;est pas valide',
    'Download_file' => 'Télécharger',
    'Video_format' => 'Le format',
    'Internet_connection_search_error' => 'La recherche ne peut pas être terminée, vérifiez la connexion Internet et réessayez.',
	'not_link_media' => 'Le lien est brisé ou mal écrit',
	'not_service_media' => 'Ce service n&#39;est pas disponible pour le moment',
	'Menu_header' => 'Menu',
	'Terms_of_Use' => 'Conditions d&#39;utilisation',
	'Privacy_Policy' => 'Politique de confidentialité',
	'Menu_header' => 'Menu',
	'Back_search' => 'Revenir',
	'languages_header' => 'langage',
	'Text_1' => 'Téléchargeur de vidéos en ligne',
	'Text_2' => 'Téléchargez des vidéos de YouTube, Instagram, Facebook, Twitter et de nombreux autres sites Web',
	'Enter_url' => 'Entrez le lien vidéo...',
	'Get_link_btn' => 'OBTENIR DES TÉLÉCHARGEMENTS LINK',
	'Get_link_btn_load' => 'Chargeur ...',
	'help_home' => '¿Besoin d&#39;aide pour télécharger des vidéos?',
	'site_Supported' => 'Voir les sites compatibles que nous avons <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => 'Voir les sites compatibles que nous avons ('.websites_supported().')',
	'click_more_home' => 'Voir tous les sites supportés',
	'help_page' => 'Étapes pour télécharger des vidéos',
	'text_down_1' => 'FORMAT',
	'text_down_2' => 'Qualité',
	'text_down_3' => 'TAILLE',
	'no_bot_user' => 'Vérifiez que je ne suis pas un bot',
	'history' => 'L&#39;histoire',
	'Settings' => 'Réglages',
	'Sign_off' => 'Déconnexion',
	'login' => 'S&#39;identifier',
	'register' => 'registre',
	'share' => 'Partager',
	'url_share' => 'URL de partage:',
	'original_url' => 'URL d&#39;origine:',
	'copy' => 'copie',
	'source_views' => 'Source de vues',
	'empty_modal' => 'Vous n&#39;avez pas encore d&#39;histoire',
	'invalid_username_or_password' => 'Nom d&#39;utilisateur ou mot de passe invalide',
	'reset_password' => 'réinitialiser le mot de passe',
	'email_sent' => 'E-mail envoyé avec succès',
    'email_not_exist' => 'Email n&#39;existe pas',
    'username' => 'Nom d&#39;utilisateur',
    'password' => 'Mot de passe',
    'email' => 'Email',
    'terms__privacy' => 'J&#39;accepte les conditions d&#39;utilisation et la politique de confidentialité',
	'please_wait' => 'S&#39;il vous plaît, attendez..',
	'please_check_details' => 'S&#39;il vous plaît vérifier les détails',
	'username_is_taken' => 'Le nom d&#39;utilisateur est pris',
	'username_invalid_characters' => 'Nom d&#39;utilisateur invalide',
    'email_exists' => 'Cet e-mail est déjà utilisée',
    'email_invalid_characters' => 'Le courriel est invalide',
	'successfully_joined_desc' => 'Inscription réussi! Nous vous avons envoyé un courrier électronique. Veuillez vérifier votre boîte de réception / spam pour vérifier votre compte.',	
	'we_have_a_problem' => 'Nous avons un problème, essayez à nouveau',
	'got_your_password' => 'Vous avez votre mot de passe?',
	'request_new_password' => 'Demander un nouveau mot de passe',
	'incorrect_information' => 'Information incorrecte',
	'password_not_match' => 'Le mot de passe ne correspond pas',
    'password_is_short' => 'Le mot de passe est trop court',
	'confirm_password' => 'Confirmez le mot de passe',
	'confirm_email' => 'Un email a été envoyé avec le nouveau mot de passe',
	'confirm_email_error' => 'il y avait une erreur pour vérifier vos données',	
	'info_plataforma' => ''.$config['name_site'].' Vous pouvez télécharger des vidéos gratuites à partir des sites les plus populaires, par exemple: Youtube, Dailymotion, Facebook, Instagram, Vimeo, etc. Après un simple clic, la vidéo sera affichée avec tous les formats disponibles, tels que MP4, FLV, 3GP, WMV, WEBM, MP3, etc. Donc, tout ce que vous avez à faire est de télécharger les vidéos dans votre format préféré. ',	
	'Support_plan' => 'Soutien',	
	'Support_plan_1' => 'Téléchargements illimités',	
	'Support_plan_2' => 'Conception facile à utiliser',	
	'Support_plan_3' => 'Historique de téléchargement',	
	'Support_plan_4' => 'Statistiques de vos liens partagés',
	'Analyzing_video_links' => 'Analyse des liens vidéo',
	'info_plataforma_2' => ''.$config['name_site'].' C&#39;est un site web gratuit pour télécharger des vidéos. Aucune installation de logiciel n&#39;est requise. Il vous suffit de nous fournir un lien contenant la vidéo que vous souhaitez télécharger. Cliquez sur le bouton Télécharger, alors tout est fini!',	
	'info_plataforma_3' => 'Téléchargement vidéo illimité et haute vitesse Télécharger des audios à partir de YouTube, TED, Soundcloud, Bandcamp',
	'Online_Video_Downloader' => 'Télécharger la vidéo en ligne',
	'Any_Video_ite' => 'N&#39;importe quelle vidéo, n&#39;importe quel site',
	'Download_Audios' => 'Télécharger des audios',
	'report_link_1' => 'Désolé, quelque chose s&#39;est mal passé, nous n&#39;avons trouvé aucune vidéo sur votre lien.',
	'report_link_2' => 'Voici ce que vous avez entré:',
	'report_link_3' => 'L&#39;erreur est',
	'report_link_4' => 'Consultez le lien précédent pour vous assurer qu’une vidéo non privée fonctionne avant de la placer dans le programme de téléchargement.',
	'report_link_5' => 'Envoyer le rapport',
	'message_link_ok' => 'Merci de nous aider :)',	
);

$name_lang 	= 'français';
$url_lang 	= 'french';
$img_lang 	= 'https://i.imgur.com/g8URijh.png';
  	
?>

