<?php


$lang_text      = array(
    '500_desc' => 'Fehler bei der Datenbank',
    '500_title' => 'Diese Seite ist nicht',
    '404_desc' => 'Diese Seite ist nicht',
    '404_title' => '404',
    '404_text' => 'nicht!!!',
    'Error_1' => 'Fehler!',
    'Error_2' => 'Die Informationen sind nicht gültig',
    'Download_file' => 'Herunterladen',
    'Video_format' => 'Formatieren',
    'Internet_connection_search_error' => 'Die Suche kann nicht abgeschlossen werden. Überprüfen Sie die Internetverbindung und versuchen Sie es erneut',
	'not_link_media' => 'Der Link ist defekt oder falsch geschrieben',
	'not_service_media' => 'Dieser Service ist momentan nicht verfügbar',
	'Menu_header' => 'Menü',
	'Terms_of_Use' => 'Nutzungsbedingungen',
	'Privacy_Policy' => 'Datenschutzrichtlinie',
	'Menu_header' => 'Menü',
	'Back_search' => 'Zurück',
	'languages_header' => 'Sprache',
	'Text_1' => 'Online-Video-Downloader',
	'Text_2' => 'Laden Sie Videos von YouTube, Instagram, Facebook, Twitter und vielen anderen Websites herunter',
	'Enter_url' => 'Geben Sie den Videolink ein...',
	'Get_link_btn' => 'LADEN SIE DOWNLOADS',
	'Get_link_btn_load' => 'Ladegerät...',
	'help_home' => '¿Sie benötigen Hilfe, um Videos herunterzuladen?',
	'site_Supported' => 'Sehen Sie die kompatiblen Websites, die wir haben <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => 'Sehen Sie die kompatiblen Websites, die wir haben ('.websites_supported().')',
	'click_more_home' => 'Alle unterstützten Sites anzeigen',
	'help_page' => 'Schritte zum Herunterladen von Videos',
	'text_down_1' => 'FORMAT',
	'text_down_2' => 'QUALITÄT',
	'text_down_3' => 'GRÖSSE',
	'no_bot_user' => 'Stellen Sie sicher, dass ich kein Bot bin',
	'history' => 'Geschichte',
	'Settings' => 'die Einstellungen',
	'Sign_off' => 'Ausloggen',
	'login' => 'Einloggen',
	'register' => 'Registrieren',
	'share' => 'Aktie',
	'url_share' => 'URL teilen:',
	'original_url' => 'Ursprüngliche URL:',
	'copy' => 'Kopieren',
	'source_views' => 'Quelle der Ansichten',
	'empty_modal' => 'Sie haben noch keine Geschichte',
	'invalid_username_or_password' => 'ungültiger Benutzername oder Passwort',
	'reset_password' => 'Passwort zurücksetzen',
	'email_sent' => 'Email wurde erfolgreich Versendet',
    'email_not_exist' => 'E-Mail existiert nicht',
    'username' => 'Nutzername',
    'password' => 'Passwort',
    'email' => 'Email',
    'terms__privacy' => 'Ich stimme den Nutzungsbedingungen und Datenschutzbestimmungen zu',
	'please_wait' => 'Warten Sie mal..',
	'please_check_details' => 'Bitte überprüfen Sie die Details',
	'username_is_taken' => 'Benutzername ist vergeben',
	'username_invalid_characters' => 'Ungültige Zeichen für den Benutzernamen',
    'email_exists' => 'Diese E-Mail-Adresse wird schon verwendet',
    'email_invalid_characters' => 'E-Mail ist ungültig',
	'successfully_joined_desc' => 'Registrierung erfolgreich! Wir haben dir eine E-Mail gesendet.',	
	'we_have_a_problem' => 'Wir haben ein Problem, versuchen Sie es erneut',
	'got_your_password' => 'Hast du dein Passwort?',
	'request_new_password' => 'Fordere ein neues Passwort an',
	'incorrect_information' => 'Falsche Angaben',
	'password_not_match' => 'Passwort stimmt nicht überein',
    'password_is_short' => 'Das Passwort ist zu kurz',
	'confirm_password' => 'Passwort bestätigen',
	'confirm_email' => 'Eine E-Mail wurde mit dem neuen Passwort gesendet',
	'confirm_email_error' => 'Bei der Überprüfung Ihrer Daten ist ein Fehler aufgetreten',
	'info_plataforma' => ''.$config['name_site'].' Sie können kostenlose Videos von den beliebtesten Websites herunterladen, z. B. Youtube, Dailymotion, Facebook, Instagram, Vimeo usw. Nach einem Klick wird das Video mit allen verfügbaren Formaten wie MP4, FLV, 3GP, WMV, WEBM, MP3 usw. angezeigt. Sie müssen also nur die Videos in Ihrem bevorzugten Format herunterladen. ',	
	'Support_plan' => 'Unterstützung',	
	'Support_plan_1' => 'Unbegrenzte Downloads',	
	'Support_plan_2' => 'Einfach zu bedienendes Design',	
	'Support_plan_3' => 'Verlauf herunterladen',	
	'Support_plan_4' => 'Statistiken Ihrer freigegebenen Links',
	'Analyzing_video_links' => 'Videolinks analysieren',
	'info_plataforma_2' => ''.$config['name_site'].' Es ist eine kostenlose Online-Website zum Herunterladen von Videos. Es ist keine Softwareinstallation erforderlich. Sie müssen uns nur einen Link bereitstellen, der das Video enthält, das Sie herunterladen möchten. Klicken Sie auf den Download-Button, dann ist alles erledigt!',	
	'info_plataforma_3' => 'Unbegrenzter und schneller Video-Download Laden Sie Audios von YouTube, TED, Soundcloud, Bandcamp herunter',
	'Online_Video_Downloader' => 'Video online herunterladen',
	'Any_Video_ite' => 'Jedes Video, jede Site',
	'Download_Audios' => 'Laden Sie Audios herunter',
	'report_link_1' => 'Leider ist ein Fehler aufgetreten. Wir konnten kein Video auf Ihrem Link finden.',
	'report_link_2' => 'Folgendes haben Sie eingegeben:',
	'report_link_3' => 'Fehler ist',
	'report_link_4' => 'Besuchen Sie den vorherigen Link, um sicherzustellen, dass es ein nicht privates Video gibt, das funktioniert, bevor Sie es in das Download-Programm aufnehmen.',
	'report_link_5' => 'Bericht senden',
	'message_link_ok' => 'Danke, dass Sie uns geholfen haben :)',	
);

$name_lang 	= 'deutsch';
$url_lang 	= 'german';
$img_lang 	= 'https://i.imgur.com/fwaPN7g.png';
  	
?>

