<?php


$lang_text      = array(
    '500_desc' => 'Errore nel database.',
    '500_title' => 'Questa pagina non è',
    '404_desc' => 'Questa pagina non è',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Errore!',
    'Error_2' => 'l&#39;informazione non è valida',
    'Download_file' => 'Scaricare',
    'Video_format' => 'Formato',
    'Internet_connection_search_error' => 'La ricerca non può essere completata, controlla la connessione Internet e riprova',
	'not_link_media' => 'Il collegamento è rotto o scritto male',
	'not_service_media' => 'Questo servizio non è disponibile al momento',
	'Menu_header' => 'Menu',
	'Terms_of_Use' => 'Condizioni d&#39;uso',
	'Privacy_Policy' => 'Politica sulla privacy',
	'Menu_header' => 'Menu',
	'Back_search' => 'ritorno',
	'languages_header' => 'lingua',
	'Text_1' => 'Downloader video online',
	'Text_2' => 'Scarica video da YouTube, Instagram, Facebook, Twitter e molti altri siti web',
	'Enter_url' => 'Inserisci il link del video ...',
	'Get_link_btn' => 'OTTIENI IL LINK DEI DOWNLOAD',
	'Get_link_btn_load' => 'Caricabatterie ...',
	'help_home' => 'Hai bisogno di aiuto per scaricare video?',
	'site_Supported' => 'Guarda i siti compatibili che abbiamo <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => 'Guarda i siti compatibili che abbiamo ('.websites_supported().')',
	'click_more_home' => 'Vedi tutti i siti supportati',
	'help_page' => 'Passi per scaricare video',
	'text_down_1' => 'FORMATO',
	'text_down_2' => 'QUALITA &#39;',
	'text_down_3' => 'DIMENSIONE',
	'no_bot_user' => 'Verifica di non essere un bot',
	'history' => 'Storia',
	'Settings' => 'impostazioni',
	'Sign_off' => 'disconnessione',
	'login' => 'Accesso',
	'register' => 'Registrare',
	'share' => 'Condividere',
	'url_share' => 'Condividi url:',
	'original_url' => 'URL originale:',
	'copy' => 'copia',
	'source_views' => 'Fonte di vista',
	'empty_modal' => 'Non hai ancora una storia',
	'invalid_username_or_password' => 'Nome utente o password errati',
	'reset_password' => 'Resetta la password',
	'email_sent' => 'email inviata correttamente',
    'email_not_exist' => 'L&#39;e-mail non esiste',
    'username' => 'Nome utente',
    'password' => 'Parola d&#39;ordine',
    'email' => 'E-mail',
    'terms__privacy' => 'Accetto i termini di utilizzo e l&#39;informativa sulla privacy',
	'please_wait' => 'Attendere prego..',
	'please_check_details' => 'Si prega di verificare i dettagli',
	'username_is_taken' => 'Il nome utente è preso',
	'username_invalid_characters' => 'Caratteri del nome utente non validi',
    'email_exists' => 'Questa e-mail è già in uso',
    'email_invalid_characters' => 'L&#39;email non è valida',
	'successfully_joined_desc' => 'Registrazione effettuata con successo! Ti abbiamo inviato un&#39;email, controlla la tua casella di posta / spam per verificare il tuo account.',	
	'we_have_a_problem' => 'Abbiamo un problema riprovare',
	'got_your_password' => 'Hai la tua password?',
	'request_new_password' => 'Richiedi una nuova password',
	'incorrect_information' => 'Informazioni errate',
	'password_not_match' => 'La password non corrisponde',
    'password_is_short' => 'La password è troppo corta',
	'confirm_password' => 'conferma password',
	'confirm_email' => 'Un&#39;email è stata inviata con la nuova password',
	'confirm_email_error' => 'c&#39;è stato un errore per verificare i tuoi dati',
	'info_plataforma' => ''.$config['name_site'].' Puoi scaricare video gratuiti dai siti più popolari, ad esempio: Youtube, Dailymotion, Facebook, Instagram, Vimeo Etc. Dopo un singolo clic, il video verrà visualizzato insieme a tutti i formati disponibili, come MP4, FLV, 3GP, WMV, WEBM, MP3, ecc. Quindi, tutto ciò che devi fare è scaricare i video nel tuo formato preferito. ',	
	'Support_plan' => 'supporto',	
	'Support_plan_1' => 'Download illimitati',	
	'Support_plan_2' => 'Design facile da usare',	
	'Support_plan_3' => 'Cronologia di download',	
	'Support_plan_4' => 'Statistiche dei tuoi collegamenti condivisi',
	'Analyzing_video_links' => 'Analizzando i collegamenti video',
	'info_plataforma_2' => ''.$config['name_site'].' È un sito Web online gratuito per scaricare video. Non è richiesta l&#39;installazione di software. Devi solo fornirci un link che contiene il video che vuoi scaricare. Fare clic sul pulsante Download, quindi le cose sono fatte!',	
	'info_plataforma_3' => 'Download video illimitato e ad alta velocità Scarica audio da YouTube, TED, Soundcloud, Bandcamp',
	'Online_Video_Downloader' => 'Scarica video online',
	'Any_Video_ite' => 'Qualsiasi video, qualsiasi sito',
	'Download_Audios' => 'Scarica audio',
	'report_link_1' => 'Spiacenti, qualcosa è andato storto, non siamo riusciti a trovare alcun video sul tuo link.',
	'report_link_2' => 'Ecco cosa hai inserito:',
	'report_link_3' => 'L&#39;errore è',
	'report_link_4' => 'Visita il link precedente per assicurarti che ci sia un video non privato che funzioni prima di inserirlo nel programma di download.',
	'report_link_5' => 'Invia rapporto',
	'message_link_ok' => 'Grazie per averci aiutato :)',	
);

$name_lang 	= 'Italiano';
$url_lang 	= 'italian';
$img_lang 	= 'https://i.imgur.com/omxxmye.png';
  	
?>

