<?php


$lang_text      = array(
    '500_desc' => 'Erro com o banco de dados.',
    '500_title' => 'Esta página não é.',
    '404_desc' => 'Esta página não é.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Erro!',
    'Error_2' => 'a informação não é válida',
    'Download_file' => 'Baixar',
    'Video_format' => 'Formato',
    'Internet_connection_search_error' => 'A pesquisa não pode ser concluída, verifique a conexão com a Internet e tente novamente',
	'not_link_media' => 'O link está quebrado ou errado.',
	'not_service_media' => 'Este serviço não está disponível no momento',
	'Menu_header' => 'cardápio',
	'Terms_of_Use' => 'Termos de uso',
	'Privacy_Policy' => 'Política de privacidade',
	'Menu_header' => 'cardápio',
	'Back_search' => 'Voltar',
	'languages_header' => 'Idioma',
	'Text_1' => 'Downloader de vídeo on-line',
	'Text_2' => 'Baixe vídeos do YouTube, Instagram, Facebook, Twitter e muitos outros sites',
	'Enter_url' => 'Digite o link do vídeo...',
	'Get_link_btn' => 'GET DOWNLOADS LINK',
	'Get_link_btn_load' => 'Carregador...',
	'help_home' => 'Precisa de ajuda para baixar vídeos?',
	'site_Supported' => 'Veja os sites compatíveis que temos <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => 'Veja os sites compatíveis que temos ('.websites_supported().')',
	'click_more_home' => 'Veja todos os sites compatíveis',
	'help_page' => 'Etapas para baixar vídeos',
	'text_down_1' => 'FORMATO',
	'text_down_2' => 'QUALIDADE',
	'text_down_3' => 'TAMANHO',
	'no_bot_user' => 'Verifique se eu não sou um bot',
	'history' => 'História',
	'Settings' => 'Definições',
	'Sign_off' => 'Sair',
	'login' => 'Entrar',
	'register' => 'registo',
	'share' => 'Compartilhar',
	'url_share' => 'Compartilhar url:',
	'original_url' => 'URL original:',
	'copy' => 'cópia de',
	'source_views' => 'Fonte de visualizações',
	'empty_modal' => 'Você ainda não tem um histórico',
	'invalid_username_or_password' => 'nome de usuário ou senha inválidos',
	'reset_password' => 'Redefinir Senha',
	'email_sent' => 'E-mail enviado com sucesso',
    'email_not_exist' => 'E-mail não existe',
    'username' => 'Nome de usuário',
    'password' => 'Senha',
    'email' => 'E-mail',
    'terms__privacy' => 'Eu concordo com os termos de uso e política de privacidade',
	'please_wait' => 'Por favor, espere..',
	'please_check_details' => 'Por favor verifique os detalhes',
	'username_is_taken' => 'O nome de usuário já está em uso',
	'username_invalid_characters' => 'Caracteres de nome de usuário inválidos',
    'email_exists' => 'Esse email já está em uso',
    'email_invalid_characters' => 'Email inválido',
	'successfully_joined_desc' => 'Registro bem sucedido! Enviamos um e-mail para você. Verifique sua caixa de entrada / spam para verificar sua conta.',	
	'we_have_a_problem' => 'Nós temos um problema, tente novamente',
	'got_your_password' => 'Tem sua senha?',
	'request_new_password' => 'requira nova senha',
	'incorrect_information' => 'Informação incorreta',
	'password_not_match' => 'Senha não corresponde',
    'password_is_short' => 'A senha é muito curta',
	'confirm_password' => 'Confirme a Senha',
	'confirm_email' => 'Um email foi enviado com a nova senha',
	'confirm_email_error' => 'houve um erro para verificar seus dados',
	'info_plataforma' => ''.$config['name_site'].' Você pode baixar gratuitamente vídeos dos sites mais populares, por exemplo: Youtube, Dailymotion, Facebook, Instagram, Vimeo Etc. Após um único clique, o vídeo será exibido junto com todos os formatos disponíveis, como MP4, FLV, 3GP, WMV, WEBM, MP3, etc. Então, tudo que você precisa fazer é baixar os vídeos em seu formato preferido. ',	
	'Support_plan' => 'Suporte',	
	'Support_plan_1' => 'Downloads Ilimitados',	
	'Support_plan_2' => 'Fácil de usar design...',	
	'Support_plan_3' => 'Histórico de download',	
	'Support_plan_4' => 'Estatísticas dos seus links compartilhados',
	'Analyzing_video_links' => 'Analisando links de vídeo',
	'info_plataforma_2' => ''.$config['name_site'].' É um site online gratuito para baixar vídeos. Nenhuma instalação de software é necessária. Você só precisa nos fornecer um link que contém o vídeo que você deseja baixar. Clique no botão Download, então as coisas estão feitas!',	
	'info_plataforma_3' => 'Download de vídeo ilimitado e de alta velocidade Download de áudios do YouTube, TED, Soundcloud, Bandcamp',
	'Online_Video_Downloader' => 'Baixe o vídeo online',
	'Any_Video_ite' => 'Qualquer vídeo, qualquer site',
	'Download_Audios' => 'Baixar áudios',
	'report_link_1' => 'Desculpe, algo deu errado, não conseguimos encontrar nenhum vídeo em seu link.',
	'report_link_2' => 'Aqui está o que você digitou:',
	'report_link_3' => 'Erro é',
	'report_link_4' => 'Visite o link anterior para se certificar de que há um vídeo não privado que funciona antes de colocá-lo no programa de download.',
	'report_link_5' => 'Enviar relatório',
	'message_link_ok' => 'Obrigado por nos ajudar :)',	
);

$name_lang 	= 'Portugues';
$url_lang 	= 'portuguese';
$img_lang 	= 'https://i.imgur.com/F2xDxWq.png';
  	
?>

