<?php


$lang_text      = array(
    '500_desc' => 'Error con la Base de datos.',
    '500_title' => 'Esta página no está .',
    '404_desc' => 'Esta página no está .',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'la información no es válida',
    'Download_file' => 'Descargar',
    'Video_format' => 'Formato',
    'Internet_connection_search_error' => 'No se puede completar la búsqueda, compruebe la conexión a Internet y vuelva a intentarlo',
	'not_link_media' => 'El Link está roto ó Esta mal escrito',
	'not_service_media' => 'Este servicio no está disponible por el momento',
	'Menu_header' => 'Menu',
	'Terms_of_Use' => 'Términos de Uso',
	'Privacy_Policy' => 'Política de privacidad',
	'Menu_header' => 'Menu',
	'Back_search' => 'Volver',
	'languages_header' => 'Idioma',
	'Text_1' => 'Descargador de video en línea',
	'Text_2' => 'Descargue videos de YouTube, Instagram, Facebook, Twitter y muchos otros sitios web',
	'Enter_url' => 'Ingrese el enlace del video ...',
	'Get_link_btn' => 'OBTENER DESCARGAS LINK',
	'Get_link_btn_load' => 'Cargador...',
	'help_home' => '¿Necesitas ayuda para descargar vídeos?',
	'site_Supported' => 'Mira los sitios compatibles que tenemos <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => 'Mira los sitios compatibles que tenemos ('.websites_supported().')',
	'click_more_home' => 'Ver todos los sitios soportados',
	'help_page' => 'Pasos para descargar vídeos',
	'text_down_1' => 'FORMATO',
	'text_down_2' => 'CALIDAD',
	'text_down_3' => 'TAMAÑO',
	'no_bot_user' => 'Verificar  no soy un bot',
	'history' => 'Historia',
	'Settings' => 'Ajustes',
	'Sign_off' => 'Cerrar sesión',
	'login' => 'Iniciar sesión',
	'register' => 'Registro',
	'share' => 'Compartir',
	'url_share' => 'Compartir url:',
	'original_url' => 'URL original:',
	'copy' => 'copiar',
	'source_views' => 'Fuente de vistas',
	'empty_modal' => 'Aún no tienes una historia.',
	'invalid_username_or_password' => 'usuario o contraseña invalido',
	'reset_password' => 'Restablecer la contraseña',
	'email_sent' => 'E-mail enviado correctamente',
    'email_not_exist' => 'E-mail no existe',
    'username' => 'Nombre de usuario',
    'password' => 'Contraseña',
    'email' => 'E-mail',
    'terms__privacy' => 'Acepto los términos de uso y política de privacidad.',
	'please_wait' => 'Por favor espera..',
	'please_check_details' => 'Por favor revise los detalles',
	'username_is_taken' => 'Nombre de usuario es tomado',
	'username_invalid_characters' => 'Caracteres de usuario inválidos',
    'email_exists' => 'Este correo electrónico ya está en uso',
    'email_invalid_characters' => 'El correo electrónico es invalido',
	'successfully_joined_desc' => '¡Registro exitoso! Le hemos enviado un correo electrónico. Revise su bandeja de entrada / correo no deseado para verificar su cuenta.',	
	'we_have_a_problem' => 'Tenemos un problema, inténtalo de nuevo.',
	'got_your_password' => '¿Tienes tu contraseña?',
	'request_new_password' => 'Pide nueva contraseña',
	'incorrect_information' => 'Información incorrecta',
	'password_not_match' => 'La contraseña no coincide',
    'password_is_short' => 'La contraseña es demasiado corta',
	'confirm_password' => 'Confirmar contraseña',
	'confirm_email' => 'Se ha enviado un correo electrónico con la nueva contraseña.',
	'confirm_email_error' => 'Hubo un error al verificar sus datos.',	
	'info_plataforma' => ''.$config['name_site'].' puede descargar gratis vídeos a partir de los sitios mas populares, por ejemplo: Youtube, dailymotion, Facebook, instagram, Vimeo  étc. Después de un solo clic, el vídeo se mostrará junto con todos los formatos disponibles, tales como MP4, FLV, 3GP, WMV, WEBM, MP3, etc. Así que, todo lo que necesitas hacer es descargar los vídeos en tu formato preferido. ',	
	'Support_plan' => 'Soporte',	
	'Support_plan_1' => 'Descargas ilimitadas',	
	'Support_plan_2' => 'Diseño facil de manejar',	
	'Support_plan_3' => 'Historial de descargas',
	'Support_plan_4' => 'Estadísticas de tus enlaces compartidos.',		
	'Analyzing_video_links' => 'Analizando enlaces de vídeo',	
	'info_plataforma_2' => ''.$config['name_site'].' es un sitio web gratuito en línea para descargar videos. No se requiere instalación de software. Solo debe proporcionarnos un enlace que contenga el video que desea descargar. Haga clic en el botón Descargar, entonces las cosas están hechas!',	
	'info_plataforma_3' => 'Descarga de video ilimitada y de alta velocidad Descarga audios de YouTube, TED, Soundcloud, Bandcamp',
	'Online_Video_Downloader' => 'Descarga de video en línea',
	'Any_Video_ite' => 'Cualquier video, cualquier sitio',
	'Download_Audios' => 'Descargar audios',
	'report_link_1' => 'Lo sentimos, algo salió mal, no pudimos encontrar ningún video en su enlace.',
	'report_link_2' => 'Aquí está lo que has introducido:',
	'report_link_3' => 'Error es',
	'report_link_4' => 'Visite el enlace anterior para asegurarse de que haya un video no privado que funcione antes de ponerlo en el programa de descarga.',
	'report_link_5' => 'Enviar reporte',
	'message_link_ok' => 'Gracias por ayudarnos :)',
);

$name_lang 	= 'Español';
$url_lang 	= 'spanish';
$img_lang 	= 'https://i.imgur.com/yVZWppU.png';
  	
?>

