<?php


$lang_text      = array(
    '500_desc' => 'Veritabanı ile ilgili hata.',
    '500_title' => 'Bu sayfa değil',
    '404_desc' => 'Bu sayfa değil',
    '404_title' => '404',
    '404_text' => 'hayır!!!',
    'Error_1' => 'hata!',
    'Error_2' => 'bilgi geçerli değil',
    'Download_file' => 'indir',
    'Video_format' => 'biçim',
    'Internet_connection_search_error' => 'Arama tamamlanamadı, İnternet bağlantısını kontrol edip tekrar deneyin.',
	'not_link_media' => 'Link bozuk veya yanlış yazılmış',
	'not_service_media' => 'Bu hizmet şu anda mevcut değil',
	'Menu_header' => 'menü',
	'Terms_of_Use' => 'Kullanım şartları',
	'Privacy_Policy' => 'Gizlilik politikası',
	'Menu_header' => 'menü',
	'Back_search' => 'dönüş',
	'languages_header' => 'dil',
	'Text_1' => 'Çevrimiçi video indirici',
	'Text_2' => 'YouTube, Instagram, Facebook, Twitter ve diğer birçok web sitesinden videolar indirin',
	'Enter_url' => 'Video bağlantısını girin...',
	'Get_link_btn' => 'DOWNLOAD LINK ALIN',
	'Get_link_btn_load' => 'Şarj aleti...',
	'help_home' => '¿Video indirmek için yardıma ihtiyacınız var?',
	'site_Supported' => 'Sahip olduğumuz uyumlu sitelere bakın <span class="websites_supported">'.websites_supported().'</span>',
	'site_Supported_page' => 'Sahip olduğumuz uyumlu sitelere bakın ('.websites_supported().')',
	'click_more_home' => 'Desteklenen tüm sitelere bakın',
	'help_page' => 'Videoları indirmek için adımlar',
	'text_down_1' => 'BİÇİM',
	'text_down_2' => 'KALİTE',
	'text_down_3' => 'BOYUT',
	'no_bot_user' => 'Bir bot olmadığımı doğrula',
	'history' => 'Tarihçe',
	'Settings' => 'Ayarlar',
	'Sign_off' => 'oturumu Kapat',
	'login' => 'Oturum aç',
	'register' => 'Kayıt olmak',
	'share' => 'Pay',
	'url_share' => 'URL paylaş:',
	'original_url' => 'Orijinal URL:',
	'copy' => 'kopya',
	'source_views' => 'Görüşlerin kaynağı',
	'empty_modal' => 'Henüz bir geçmişiniz yok',
	'invalid_username_or_password' => 'Geçersiz kullanıcı adı veya şifre',
	'reset_password' => 'Şifreyi yenile',
	'email_sent' => 'E-posta başarıyla gönderildi',
    'email_not_exist' => 'E-posta mevcut değil',
    'username' => 'Kullanıcı adı',
    'password' => 'Parola',
    'email' => 'E-mail',
    'terms__privacy' => 'Kullanım koşullarını ve gizlilik politikasını kabul ediyorum',
	'please_wait' => 'Lütfen bekle..',
	'please_check_details' => 'Lütfen detayları kontrol et',
	'username_is_taken' => 'Kullanıcı adı alınmış',
	'username_invalid_characters' => 'Geçersiz kullanıcı adı karakterleri',
    'email_exists' => 'Bu e-posta zaten kullanılıyor',
    'email_invalid_characters' => 'E-posta geçersiz',
	'successfully_joined_desc' => 'Kayıt başarılı! Size bir e-posta gönderdik, hesabınızı doğrulamak için lütfen gelen kutunuzu / spam’ı kontrol edin.',	
	'we_have_a_problem' => 'Tekrar denediğimizde sorun yaşıyoruz',
	'got_your_password' => 'Şifrenizi aldınız mı',
	'request_new_password' => 'yeni şifre isteği',
	'incorrect_information' => 'Yanlış bilgi',
	'password_not_match' => 'Şifre eşleşmiyor',
    'password_is_short' => 'Şifre çok kısa',
	'confirm_password' => 'Şifreyi Onayla',
	'confirm_email' => 'Yeni şifre ile bir e-posta gönderildi',
	'confirm_email_error' => 'verilerinizi doğrulamak için bir hata oluştu',
	'info_plataforma' => ''.$config['name_site'].' En popüler sitelerden ücretsiz videolar indirebilirsiniz, örneğin: Youtube, Dailymotion, Facebook, Instagram, Vimeo Etc. Tek bir tıklamanın ardından video, MP4, FLV, 3GP, WMV, WEBM, MP3, vb. Kullanılabilir tüm biçimlerle birlikte görüntülenir. Yani, yapmanız gereken tek şey videoları tercih ettiğiniz biçimde indirmek. ',	
	'Support_plan' => 'destek',	
	'Support_plan_1' => 'Sınırsız indirme',	
	'Support_plan_2' => 'Kullanımı kolay tasarım',	
	'Support_plan_3' => 'İndirme geçmişi',	
	'Support_plan_4' => 'Paylaşılan bağlantılarınızın istatistikleri',		
	'Analyzing_video_links' => 'Video bağlantılarını analiz etme',
	'info_plataforma_2' => ''.$config['name_site'].' Video indirmek için ücretsiz bir web sitesidir. Yazılım yüklemesi gerekmez. Bize indirmek istediğiniz videoyu içeren bir bağlantı sağlamanız yeterli. İndir düğmesine tıklayın, ardından işler tamamlandı!',	
	'info_plataforma_3' => 'Sınırsız ve yüksek hızlı video indirme YouTube, TED, Soundcloud, Bandcamp&#39;tan ses indirin',
	'Online_Video_Downloader' => 'Online video indir',
	'Any_Video_ite' => 'Herhangi bir video, herhangi bir site',
	'Download_Audios' => 'Ses indir',
	'report_link_1' => 'Üzgünüz, bir şeyler ters gitti, bağlantınızda video bulamadık.',
	'report_link_2' => 'İşte ne girdiniz:',
	'report_link_3' => 'Hata',
	'report_link_4' => 'İndirme programına koymadan önce çalışan özel olmayan bir video olduğundan emin olmak için önceki bağlantıyı ziyaret edin.',
	'report_link_5' => 'Rapor gönder',
	'message_link_ok' => 'Bize yardım ettiğiniz için teşekkürler :)',	
);

$name_lang 	= 'Türk';
$url_lang 	= 'turkish';
$img_lang 	= 'https://i.imgur.com/hXssGnB.png';
  	
?>

